### ISSUE TITLE
Add support for Zowe v2 team configuration

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/zowe-client-python-sdk#148]
This epic contains all items within the [Zowe v2 Team Configuration milestone](https://github.com/zowe/zowe-client-python-sdk/milestone/36):
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-client-python-sdk/issues/134
- [ ] https://github.com/zowe/zowe-client-python-sdk/issues/136
- [ ] https://github.com/zowe/zowe-client-python-sdk/issues/74
- [ ] https://github.com/zowe/zowe-client-python-sdk/issues/73
- [ ] https://github.com/zowe/zowe-client-python-sdk/issues/72
- [ ] https://github.com/zowe/zowe-client-python-sdk/issues/135
```

**Comment by bhavukkalra** [comment]
Hey There @adam-wolfe I was looking at the projects which are available under LFX Mentorship and this one specifically caught my eye. Having past experience with python, Web Apps, REST API's and DB's. I feel like this is right up my ally of required skillset.

**Would it be possible to better describe this Epic or point me to the Stories under this epic**. So that I could get a better understanding of what are our requirements?

Are these the feature stories under v2 release? - https://github.com/zowe/zowe-client-python-sdk/milestone/36

cc - @t1m0thyj

**Comment by adam-wolfe** [comment]
Hi @bhavukkalra, that is correct.

**Comment by bhavukkalra** [comment]
Thanks for the confirmation @adam-wolfe. Currently I am working on setting up the project locally on windows 10, but getting some issues on it. I am tracking my progress here - issue #153.

Could you suggest some resources  which I could read up on to make myself  more familiar with the project or point me to the team communication channel (if any) that is used for maintaining this project?

cc- @t1m0thyj

**Comment by adam-wolfe** [comment]
Here are a few links that might be relevant:
- [Blog post on available Zowe SDKs](https://medium.com/zowe/zowe-software-development-kits-d60b8d2b2246)
- [Zowe Python SDK documentation](https://zowe-client-python-sdk.readthedocs.io/en/latest/index.html)
- [Team configuration documentation](https://docs.zowe.org/stable/user-guide/cli-using-using-team-profiles)
- [Zowe Overview](https://docs.zowe.org/stable/getting-started/overview/)

The Zowe community mostly communicates via GitHub and Slack (https://slack.openmainframeproject.org/).

**Comment by achiverram28** [comment]
Hey @adam-wolfe I found out your project under the LFX-Mentorship to be interesting and would love to contribute to your project . I am deep and an open source enthusiast , as I have dealt with Django , Flask frameworks and developed APIs using Fast-APi . I am a keen Cloud and DevOps enthusiast.

It would be great to get started and could you guide me to get started with things.
Hoping to be accepted as a mentee under you project

**Comment by adam-wolfe** [comment]
Hi @achiverram28, if you are interested, be sure to apply at https://mentorship.lfx.linuxfoundation.org/project/dcf9b5fd-a454-44de-a0cc-0949619fd7e2 by May 26, if you have not already.

Beyond reading the above docs, you might be interested in attending some of the Zowe community meetings listed in the calendar (https://lists.openmainframeproject.org/g/zowe-dev/calendar). All meetings are open to the public. The Zowe CLI squad manages Zowe CLI and the Zowe Node.js and Python SDKS and meets during the Zowe CLI standup. The TSC call might also be worth attending if you want to learn more about what is going on in the broader Zowe community.

**Comment by achiverram28** [comment]
I have applied via the LFX Mentorship.
Sure I will look into what you have said @adam-wolfe

**Comment by adam-wolfe** [comment]
Is there anything more that needs to be done to support team config?

**Comment by t1m0thyj** [comment]
Discussed with @zFernand0 and this epic is probably good to close 😋
